model_path: 'model/best.pt'
videos_path: 'videos/'
detection_conf_thresh: 0.1
gpu_avail: True #True #False
generate_detections: True #False if the YOLO annotations already present (saves compute!)
generate_jsons: True
blur_radius: 31 #increase to increase blur intensity (odd values)
output_folder: blurred_videos