model_path: 'model/best.pt'
videos_path: 'videos/'
detection_conf_thresh: 0.1
gpu_avail: False #True
vid_format: .png #or any other format supported by YOLO
vid_width: 1920
vid_height: 1080
generate_detections: False #False if the YOLO annotations already present (saves compute!)
vid_fps: 25
blur_radius: 31 #increase to increase blur intensity (odd values)
output_folder: blurred_videos